config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  # Mobile Api routes
  namespace :api do
    namespace :v1 do
    end
  end

  # Back admin routes start
  namespace :admin do
    resources :users
    resources :locations
    resources :reviews
    resources :movies
    resources :directors
    resources :actors
    # Admin root
    root to: 'application#index'
  end

  # Front routes start
  devise_for :users, only: %i[session registration], path: 'session',
                     path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  # Application root
  root to: 'admin/application#index'
  # Front routes end
end

app/controllers/admin/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:stars, :content)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :stars %>
    <%= form.number_field :stars %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/admin/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Stars</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.stars %></td>
        <td><%= review.content %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/admin/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/admin/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stars:</strong>
  <%= @review.stars %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>